version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Update lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-update
      - run:
          name: Run all tests
          command: npm test
      - run:
          name: Upload lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-upload
      - run:
          name: Lint all source and generate coverage report
          command: npm run test:prod
      - run:
          name: Build source (Rollup) and generate library
          command: npm run build
      - run:
          name: Sync coverage report
          command: npm run report-coverage
