version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: circleci/node:9.11.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run all tests
          command: npm test
      - run:
          name: Lint all source and generate coverage report
          command: npm run test:prod
      - run:
          name: Build source (Rollup) and generate library
          command: npm run build
      - run:
          name: Sync coverage report
          command: npm run report-coverage
      - run:
          name: Generate Documentation pages and upload
          command: |
            if [ $CIRCLE_BRANCH == "master" ]
            then
              npm run deploy-docs
            else
              echo "Skipping documentation deploy, as the current building branch is not master"
            fi

