name: Test, Package and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/bin/filter@master
      args: branch master
      
    - name: I'm now running a step only for master
      run: echo I'm the master now!
    
    
